name: build and upload binaries

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      
      - name: build windows binary
        run: GOOS=windows GOARCH=amd64 go build -o runcmd.exe main.go
        
      - name: build linux binary
        run: GOOS=linux GOARCH=amd64 go build -o runcmd.linux main.go
        
      - name: build mac binary
        run: GOOS=darwin GOARCH=amd64 go build -o runcmd.mac main.go
        
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: "runcmd*"
          tag_name: "main"
          #tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
